/**
 * Aggelos Frantzeskakis / AF — bilingual copy layer.
 * Light-only editorial language: precise, restrained, cinematic, and never decorative for its own sake.
 */
export type Language = "en" | "el";

export const ui = {
  en: {
    nav: { home: "Arrival", work: "Work", skills: "Skills", stack: "Stack", about: "Profile", contact: "Contact" },
    languageLabel: "Language",
    primaryNavigation: "Primary navigation",
    brandHome: "Aggelos Frantzeskakis home",
    themeLabel: "Theme",
    switchToDark: "Switch to dark theme",
    switchToLight: "Switch to light theme",

    github: "GitHub",
    linkedin: "LinkedIn",
    linkedinPending: "LinkedIn profile URL pending",
    openNavigation: "Open navigation",
    closeNavigation: "Close navigation",
    navigation: "Navigation",
    closeMenu: "Close menu",
    heroEyebrow: "Aggelos Frantzeskakis · AXON",
    heroTitle: "Software that solves",
    heroAccent: "the actual problem.",
    heroDescription: "I work with businesses and teams of any size. I find where the work is slow, manual, or expensive, then build the thing that fixes it — a booking system, a client platform, a local-AI tool, or a website that finally does its job. Independent developer, working under AXON.",
    exploreWork: "See the work",
    seeSkills: "What I build",
    nowExploring: "Based in",
    heroSignature: "Rethymno, Crete · working remotely",
    signatureStudy: "Rethymno, Crete",
    flightPath: "open to work",
    selectedWork: "Selected work",
    workTitle: "Things I built",
    workAccent: "that people use.",
    workAside: "Five projects that show the range: a booking platform running for a real shop, an AI system I build with, and tools that keep data on the device. Live demos where they exist; client code stays private.",
    workHint: "Open a card for the details.",
    skillsLabel: "What I do",
    skillsTitle: "Three kinds of",
    skillsAccent: "problem I solve.",
    skillsDescription: "Most requests land in one of these three. If yours does not, describe it anyway — the useful part is working out what actually needs building.",
    skillTabsLabel: "Skill groups",
    skillTabs: { systems: "Business systems", resilient: "Offline & local", intelligence: "AI" },
    skillContent: {
      systems: { title: "Make the daily work faster.", text: "Bookings, orders, records, admin panels — the systems a business actually runs on. I map how the work happens today, then build software that fits it instead of fighting it.", tags: ["Booking systems", "Client platforms", "Admin dashboards", "Websites"] },
      resilient: { title: "Works when the network does not.", text: "Local-first apps that keep running offline and sync when they can. It matters when the wifi is bad, the shop is busy, or the data should never leave the device.", tags: ["PWA", "Offline-first", "IndexedDB", "Local data"] },
      intelligence: { title: "AI where it earns its place.", text: "Local models through Ollama, multi-provider routing, RAG. For clients such as lawyers and agronomists, whose files cannot go to a cloud API, running the model locally is the only option that works.", tags: ["Local AI / Ollama", "RAG", "Provider routing", "Automation"] },
    },
    stackLabel: "Tech stack",
    stackTitle: "The tools",
    stackAccent: "I actually use.",
    stackAside: "What the projects on this page are built with. Not a wish list.",
    stackEvidence: "Verifiable in the repositories.",
    stackGroupLabels: ["Languages", "Product patterns", "AI direction"],
    stackNote: "Ask about anything not listed here. The stack follows the problem, not the other way round.",
    skillsToolsTitle: "The tools behind",
    skillsToolsAccent: "the work.",
    skillsToolsDescription: "The languages, frameworks, and AI runtimes used across the projects above.",
    skillsToolsNote: "Toolbox",
    skillsToolGroupLabels: ["Languages", "Web & product", "Local AI", "Delivery"],

    aboutLabel: "About",
    aboutDescription: "I’m 19, self-taught, based in Rethymno on Crete, and completing military service until October 2026. I ship software that runs in production, not tutorials. I work independently and under AXON, my own practice — which means one person handles the conversation, the build, and the support afterwards, and nothing gets lost between departments.",
    openGithub: "Open GitHub",
    copyHandle: "Copy handle",
    copied: "Copied",
    copySuccess: "GitHub handle copied",
    copyError: "Could not copy the GitHub handle",
    cvReady: "CV ready to download",
    downloadStarted: "CV download started",
    publicRepositories: "public repositories",
    preparingCv: "Preparing CV…",
    downloadCv: "Download CV",
    contactLabel: "Start a conversation",
    contactPrompt: "What is slowing you down?",
    contactTitle: "Tell me the",
    contactAccent: "problem first.",
    contactDescription: "Describe what is slow, manual, or broken. I will tell you honestly whether software is the answer and what it would take to build it.",
    backToTop: "Back to top",
    footerNote: "AF / vertical editorial portfolio",
    project: { private: "Private", public: "Public", privateKicker: "Private build", publicKicker: "Public project", openProjectPrefix: "Open details for", studyLabel: "Project study", openDetails: "Open details", fallback: "Client work — details on request.", detailFallback: "This study is generated from the current GitHub snapshot.", mixed: "Mixed", stars: "stars", forks: "forks", privateSource: "Source boundary: private", sourceGithub: "Source available on GitHub", closeDetails: "Close details", filterAll: "Everything", filterClient: "Client work", filterAi: "AI", filterOffline: "Offline-first", emptyFilter: "Nothing in this category yet. Try 'Everything'." },
    cv: { previewCode: "Document preview / 01", close: "Close CV preview", paperLabel: "Preview of the current factual CV draft", role: "Software Developer — Web & AI Systems (self-taught)", summary: "I ship software that runs in production, not tutorials: booking platforms for real businesses, offline-first PWAs, and tools that run local AI so client data never leaves the device.", selectedWork: "Selected work", capabilities: "Capabilities", currentDraft: "Full CV", grounded: "PDF · A4", draftNote: "The full document covers education, projects, the stack, and availability. Available for full-time work from November 2026.", replacementNote: "Every project listed is one I built and can walk you through, line by line.", confirmDetails: "Ask me anything by email", format: "PDF · A4", keepBrowsing: "Keep browsing", download: "Download CV", openDirectly: "Open PDF directly" },
    loader: { aria: "Loading Aggelos portfolio", topLeft: "AF / digital craft", topRight: "Portfolio / 2026", calibrating: "Calibrating the flight path", opening: "Opening the portfolio", signalCalibrating: "CALIBRATING", signalOpening: "OPENING", bottomLeft: "Loading a useful space", bottomRight: "Scroll when ready ↓" },
    form: { name: "Your name", namePlaceholder: "Name", email: "Your email", emailPlaceholder: "you@example.com", subject: "Subject", subjectPlaceholder: "What this is about", message: "Message", messagePlaceholder: "What is slow, manual, or broken right now...", sending: "Sending securely…", sent: "Message sent. I’ll get back to you soon.", successToastTitle: "Message received", successToastDescription: "Thanks — your note is safely on its way. I’ll reply soon.", emailOpened: "Your email client should open now.", error: "Something went wrong. Please email me directly.", active: "Secure Formspree delivery is active.", fallback: "Email fallback is active until a Formspree endpoint is added.", compose: "Compose email", defaultSubject: "Portfolio collaboration", nameError: "Please enter your name (at least 2 characters).", emailError: "Please enter a valid email address.", subjectError: "Please enter a subject (at least 3 characters).", messageError: "Please enter a message (at least 10 characters)." },
  },
  el: {
    nav: { home: "Άφιξη", work: "Έργα", skills: "Ικανότητες", stack: "Stack", about: "Προφίλ", contact: "Επικοινωνία" },
    languageLabel: "Γλώσσα",
    primaryNavigation: "Κύρια πλοήγηση",
    brandHome: "Αρχική του Aggelos Frantzeskakis",
    themeLabel: "Θέμα",
    switchToDark: "Εναλλαγή σε σκοτεινό θέμα",
    switchToLight: "Εναλλαγή σε φωτεινό θέμα",

    github: "GitHub",
    linkedin: "LinkedIn",
    linkedinPending: "Αναμένεται το URL του LinkedIn",
    openNavigation: "Άνοιγμα πλοήγησης",
    closeNavigation: "Κλείσιμο πλοήγησης",
    navigation: "Πλοήγηση",
    closeMenu: "Κλείσιμο μενού",
    heroEyebrow: "Aggelos Frantzeskakis · AXON",
    heroTitle: "Λογισμικό που λύνει",
    heroAccent: "το πραγματικό πρόβλημα.",
    heroDescription: "Δουλεύω με επιχειρήσεις και ομάδες κάθε μεγέθους. Βρίσκω πού η δουλειά είναι αργή, χειροκίνητη ή ακριβή, και φτιάχνω αυτό που τη λύνει — σύστημα κρατήσεων, πλατφόρμα για πελάτες, εργαλείο με τοπικό AI ή ένα site που επιτέλους κάνει τη δουλειά του. Ανεξάρτητος developer, μέσα από την AXON.",
    exploreWork: "Δες τα έργα",
    seeSkills: "Τι φτιάχνω",
    nowExploring: "Έδρα",
    heroSignature: "Ρέθυμνο, Κρήτη · και εξ αποστάσεως",
    signatureStudy: "Ρέθυμνο, Κρήτη",
    flightPath: "δέχομαι δουλειά",
    selectedWork: "Επιλεγμένα έργα",
    workTitle: "Πράγματα που έχτισα",
    workAccent: "και χρησιμοποιούνται.",
    workAside: "Πέντε έργα που δείχνουν το εύρος: μια πλατφόρμα κρατήσεων που τρέχει για πραγματικό μαγαζί, το AI σύστημα με το οποίο χτίζω, και εργαλεία που κρατούν τα δεδομένα στη συσκευή. Live demo όπου υπάρχει· ο κώδικας πελατών μένει ιδιωτικός.",
    workHint: "Άνοιξε μια κάρτα για λεπτομέρειες.",
    skillsLabel: "Τι κάνω",
    skillsTitle: "Τρία είδη",
    skillsAccent: "προβλήματος που λύνω.",
    skillsDescription: "Τα περισσότερα αιτήματα πέφτουν σε ένα από αυτά τα τρία. Αν το δικό σου δεν πέφτει, πες το μου έτσι κι αλλιώς — το χρήσιμο κομμάτι είναι να βρούμε τι χρειάζεται πραγματικά να χτιστεί.",
    skillTabsLabel: "Ομάδες ικανοτήτων",
    skillTabs: { systems: "Συστήματα επιχείρησης", resilient: "Offline & τοπικά", intelligence: "AI" },
    skillContent: {
      systems: { title: "Κάνω την καθημερινή δουλειά πιο γρήγορη.", text: "Κρατήσεις, παραγγελίες, αρχεία, admin panel — τα συστήματα πάνω στα οποία τρέχει πραγματικά μια επιχείρηση. Καταγράφω πώς γίνεται σήμερα η δουλειά και μετά χτίζω λογισμικό που ταιριάζει σε αυτήν, αντί να την πολεμάει.", tags: ["Συστήματα κρατήσεων", "Πλατφόρμες πελατών", "Admin dashboards", "Websites"] },
      resilient: { title: "Δουλεύει και όταν δεν δουλεύει το δίκτυο.", text: "Local-first εφαρμογές που συνεχίζουν offline και συγχρονίζονται όταν μπορούν. Μετράει όταν το wifi είναι κακό, το μαγαζί έχει κίνηση, ή τα δεδομένα δεν πρέπει να φύγουν από τη συσκευή.", tags: ["PWA", "Offline-first", "IndexedDB", "Τοπικά δεδομένα"] },
      intelligence: { title: "AI εκεί που πραγματικά χρειάζεται.", text: "Τοπικά μοντέλα μέσω Ollama, multi-provider routing, RAG. Για πελάτες όπως δικηγόροι και γεωπόνοι, που τα αρχεία τους δεν μπορούν να πάνε σε cloud API, το τοπικό μοντέλο είναι η μόνη λύση που στέκει.", tags: ["Τοπικό AI / Ollama", "RAG", "Provider routing", "Αυτοματισμοί"] },
    },
    stackLabel: "Tech stack",
    stackTitle: "Τα εργαλεία",
    stackAccent: "που όντως χρησιμοποιώ.",
    stackAside: "Με αυτά είναι φτιαγμένα τα έργα αυτής της σελίδας. Όχι λίστα ευχών.",
    stackEvidence: "Επαληθεύσιμο στα repositories.",
    stackGroupLabels: ["Γλώσσες", "Product patterns", "AI κατεύθυνση"],
    stackNote: "Ρώτα με για οτιδήποτε δεν αναφέρεται εδώ. Το stack ακολουθεί το πρόβλημα, όχι το αντίστροφο.",
    skillsToolsTitle: "Τα εργαλεία πίσω από",
    skillsToolsAccent: "τη δουλειά.",
    skillsToolsDescription: "Οι γλώσσες, τα frameworks και τα AI runtimes που χρησιμοποιούνται στα έργα παραπάνω.",
    skillsToolsNote: "Εργαλειοθήκη",
    skillsToolGroupLabels: ["Γλώσσες", "Web & προϊόν", "Τοπικό AI", "Παράδοση"],

    aboutLabel: "Λίγα λόγια",
    aboutDescription: "Είμαι 19, αυτοδίδακτος, από το Ρέθυμνο, και υπηρετώ τη θητεία μου μέχρι τον Οκτώβριο του 2026. Γράφω λογισμικό που τρέχει σε παραγωγή, όχι tutorials. Δουλεύω ανεξάρτητα και μέσα από την AXON, τη δική μου δουλειά — ένας άνθρωπος κάνει τη συζήτηση, το build και την υποστήριξη μετά, χωρίς να χάνεται τίποτα ανάμεσα σε τμήματα.",
    openGithub: "Άνοιγμα GitHub",
    copyHandle: "Αντιγραφή handle",
    copied: "Αντιγράφηκε",
    copySuccess: "Το GitHub handle αντιγράφηκε",
    copyError: "Δεν ήταν δυνατή η αντιγραφή του GitHub handle",
    cvReady: "Το CV είναι έτοιμο για λήψη",
    downloadStarted: "Η λήψη του CV ξεκίνησε",
    publicRepositories: "δημόσια repositories",
    preparingCv: "Προετοιμασία CV…",
    downloadCv: "Λήψη CV",
    contactLabel: "Ξεκίνα μια συζήτηση",
    contactPrompt: "Τι σε καθυστερεί;",
    contactTitle: "Πες μου πρώτα",
    contactAccent: "το πρόβλημα.",
    contactDescription: "Περίγραψέ μου τι είναι αργό, χειροκίνητο ή χαλασμένο. Θα σου πω ειλικρινά αν το λογισμικό είναι η απάντηση και τι χρειάζεται για να γίνει.",
    backToTop: "Επιστροφή στην κορυφή",
    footerNote: "AF / κάθετο editorial portfolio",
    project: { private: "Ιδιωτικό", public: "Δημόσιο", privateKicker: "Ιδιωτικό build", publicKicker: "Δημόσιο project", openProjectPrefix: "Άνοιγμα λεπτομερειών για", studyLabel: "Μελέτη project", openDetails: "Άνοιγμα λεπτομερειών", fallback: "Δουλειά για πελάτη — λεπτομέρειες κατόπιν αιτήματος.", detailFallback: "Αυτή η μελέτη δημιουργείται από το τρέχον snapshot του GitHub.", mixed: "Mixed", stars: "stars", forks: "forks", privateSource: "Όριο πηγής: ιδιωτικό", sourceGithub: "Η πηγή είναι διαθέσιμη στο GitHub", closeDetails: "Κλείσιμο λεπτομερειών", filterAll: "Όλα", filterClient: "Για πελάτες", filterAi: "AI", filterOffline: "Offline-first", emptyFilter: "Δεν υπάρχει κάτι σε αυτή την κατηγορία ακόμα. Δοκίμασε το 'Όλα'." },
    cv: { previewCode: "Προεπισκόπηση εγγράφου / 01", close: "Κλείσιμο προεπισκόπησης CV", paperLabel: "Προεπισκόπηση του τρέχοντος factual draft CV", role: "Software Developer — Web & AI Systems (αυτοδίδακτος)", summary: "Γράφω λογισμικό που τρέχει σε παραγωγή, όχι tutorials: πλατφόρμες κρατήσεων για πραγματικές επιχειρήσεις, offline-first PWAs, και εργαλεία με τοπικό AI ώστε τα δεδομένα του πελάτη να μη φεύγουν ποτέ από τη συσκευή.", selectedWork: "Επιλεγμένα έργα", capabilities: "Ικανότητες", currentDraft: "Πλήρες CV", grounded: "PDF · A4", draftNote: "Το πλήρες έγγραφο καλύπτει σπουδές, έργα, stack και διαθεσιμότητα. Διαθέσιμος για πλήρη απασχόληση από τον Νοέμβριο του 2026.", replacementNote: "Κάθε έργο της λίστας το έχω χτίσει ο ίδιος και μπορώ να σου το εξηγήσω γραμμή προς γραμμή.", confirmDetails: "Ρώτησέ με ό,τι θες με email", format: "PDF · A4", keepBrowsing: "Συνέχισε την περιήγηση", download: "Λήψη CV", openDirectly: "Άνοιγμα PDF απευθείας" },
    loader: { aria: "Φόρτωση portfolio του Aggelos", topLeft: "AF / digital craft", topRight: "Portfolio / 2026", calibrating: "Ρυθμίζω τη διαδρομή πτήσης", opening: "Ανοίγω το portfolio", signalCalibrating: "ΡΥΘΜΙΣΗ", signalOpening: "ΑΝΟΙΓΜΑ", bottomLeft: "Φορτώνω έναν χρήσιμο χώρο", bottomRight: "Κάνε scroll όταν είσαι έτοιμος ↓" },
    form: { name: "Το όνομά σου", namePlaceholder: "Όνομα", email: "Το email σου", emailPlaceholder: "you@example.com", subject: "Θέμα", subjectPlaceholder: "Σχετικά με", message: "Μήνυμα", messagePlaceholder: "Τι είναι αργό, χειροκίνητο ή χαλασμένο αυτή τη στιγμή...", sending: "Ασφαλής αποστολή…", sent: "Το μήνυμα στάλθηκε. Θα σου απαντήσω σύντομα.", successToastTitle: "Το μήνυμα παραλήφθηκε", successToastDescription: "Ευχαριστώ — το μήνυμά σου στάλθηκε με ασφάλεια. Θα απαντήσω σύντομα.", emailOpened: "Το email client σου θα πρέπει να ανοίξει τώρα.", error: "Κάτι πήγε στραβά. Στείλε μου απευθείας email.", active: "Η ασφαλής παράδοση μέσω Formspree είναι ενεργή.", fallback: "Το email fallback είναι ενεργό μέχρι να προστεθεί Formspree endpoint.", compose: "Σύνταξη email", defaultSubject: "Συνεργασία μέσω portfolio", nameError: "Παρακαλώ εισάγετε όνομα (τουλάχιστον 2 χαρακτήρες).", emailError: "Παρακαλώ εισάγετε ένα έγκυρο email.", subjectError: "Παρακαλώ εισάγετε θέμα (τουλάχιστον 3 χαρακτήρες).", messageError: "Παρακαλώ εισάγετε μήνυμα (τουλάχιστον 10 χαρακτήρες)." },
  },
} as const;
