/**
 * Aggelos Frantzeskakis / AF — bilingual copy layer.
 * Light-only editorial language: precise, restrained, cinematic, and never decorative for its own sake.
 */
export type Language = "en" | "el";

export const ui = {
  en: {
    nav: { home: "Home", work: "Work", skills: "Skills", stack: "Stack", about: "About", contact: "Contact" },
    languageLabel: "Language",
    primaryNavigation: "Primary navigation",
    brandHome: "Aggelos Frantzeskakis home",
    themeLabel: "Theme",
    switchToDark: "Switch to dark theme",
    switchToLight: "Switch to light theme",

    github: "GitHub",
    linkedin: "LinkedIn",
    linkedinPending: "LinkedIn profile URL pending",
    openNavigation: "Open navigation",
    closeNavigation: "Close navigation",
    navigation: "Navigation",
    closeMenu: "Close menu",
    heroEyebrow: "Aggelos Frantzeskakis · Software Developer",
    heroTitle: "Make the complex",
    heroAccent: "feel alive.",
    heroDescription: "I build useful digital experiences around offline-first products, local AI, and interfaces that give ambitious ideas a clearer way to move.",
    exploreWork: "Explore the work",
    seeSkills: "See the skills",
    nowExploring: "Now exploring",
    heroSignature: "resilient products · local intelligence",
    signatureStudy: "Signature study",
    flightPath: "01 / flight path",
    selectedWork: "Selected work",
    workTitle: "Projects with",
    workAccent: "a point of view.",
    workAside: "A live selection from the current GitHub snapshot. Click a card for a focused study; private work stays clearly marked.",
    workHint: "Scroll naturally to explore each chapter.",
    skillsLabel: "Skills / current practice",
    skillsTitle: "Build the shape",
    skillsAccent: "around the signal.",
    skillsDescription: "The working directions that run through my current projects — how I approach systems, resilient products, and local intelligence.",
    skillTabsLabel: "Skill groups",
    skillTabs: { systems: "Systems", resilient: "Resilient", intelligence: "Intelligence" },
    skillContent: {
      systems: { title: "Make complexity feel enterable.", text: "I shape product systems, information hierarchies, and responsive flows so useful tools remain legible as they grow.", tags: ["Product thinking", "UX / UI", "Architecture", "Responsive web"] },
      resilient: { title: "Keep the work close.", text: "I care about local-first behavior, graceful states, and experiences that keep their dignity when the network disappears.", tags: ["PWA", "Offline-first", "IndexedDB", "Local data"] },
      intelligence: { title: "Give AI a useful place.", text: "I explore local AI, RAG, provider routing, and human-readable orchestration without hiding the system behind magic.", tags: ["Local AI", "RAG", "Provider systems", "AI workflows"] },
    },
    stackLabel: "Tech stack",
    stackTitle: "Tools for a",
    stackAccent: "living system.",
    stackAside: "Based on the languages, patterns, and AI directions represented in the current GitHub snapshot. The stack is intentionally expandable.",
    stackEvidence: "Current evidence, future room.",
    stackGroupLabels: ["Languages", "Product patterns", "AI direction"],
    stackNote: "Everything listed here comes from code I have actually shipped.",
    skillsToolsTitle: "The tools behind",
    skillsToolsAccent: "the practice.",
    skillsToolsDescription: "The tools and technologies I reach for across these projects.",
    skillsToolsNote: "Tools & technologies",
    skillsToolGroupLabels: ["Build language", "Resilient products", "Local intelligence", "Delivery craft"],

    aboutLabel: "The person behind the work",
    aboutDescription: "I’m a 19-year-old self-taught developer from Crete. I build offline-first web apps and local-AI tools, mostly in TypeScript and Python, and I care about software that stays fast, private, and legible. Most of my code lives in private repos — the public ones show how I build.",
    openGithub: "Open GitHub",
    copyHandle: "Copy handle",
    copied: "Copied",
    copySuccess: "GitHub handle copied",
    copyError: "Could not copy the GitHub handle",
    cvReady: "CV ready to download",
    downloadStarted: "CV download started",
    publicRepositories: "public repositories",
    preparingCv: "Preparing CV…",
    downloadCv: "Download CV",
    contactLabel: "Start a conversation",
    contactPrompt: "Have a good problem?",
    contactTitle: "Let’s make",
    contactAccent: "something memorable.",
    contactDescription: "Tell me what you are shaping. The next step stays direct, whether delivery runs through Formspree or your email client.",
    backToTop: "Back to top",
    footerNote: "AF / vertical editorial portfolio",
    project: { private: "Private", public: "Public", privateKicker: "Private build", publicKicker: "Public project", openProjectPrefix: "Open details for", studyLabel: "Project study", openDetails: "Open details", fallback: "A repository shaped through curiosity and iteration.", detailFallback: "This study is generated from the current GitHub snapshot.", mixed: "Mixed", stars: "stars", forks: "forks", privateSource: "Source boundary: private", sourceGithub: "Source available on GitHub", closeDetails: "Close details", filterAll: "All systems", filterTypeScript: "TypeScript", filterPwa: "PWA / Web", filterAi: "AI / Local", filterPrivate: "Private", emptyFilter: "No repositories match this technology filter. Try selecting 'All systems'." },
    cv: { previewCode: "Document preview / 01", close: "Close CV preview", paperLabel: "CV preview", role: "Software & Product Developer", summary: "I build useful digital experiences around offline-first products, local AI, resilient interfaces, and thoughtful web experiences.", selectedWork: "Selected work", capabilities: "Capabilities", currentDraft: "CV preview", grounded: "GitHub-grounded", confirmDetails: "Get in touch by email", format: "PDF · A4", keepBrowsing: "Keep browsing", download: "Download CV", openDirectly: "Open PDF directly" },
    loader: { aria: "Loading Aggelos portfolio", topLeft: "AF / digital craft", topRight: "Portfolio / 2026", calibrating: "Calibrating the flight path", opening: "Opening the portfolio", signalCalibrating: "CALIBRATING", signalOpening: "OPENING", bottomLeft: "Loading a useful space", bottomRight: "Scroll when ready ↓" },
    form: { name: "Your name", namePlaceholder: "Name", emailLabel: "Your email", emailPlaceholder: "you@example.com", emailError: "Please enter a valid email so I can reply.", subject: "Subject", subjectPlaceholder: "A good problem", message: "Message", messagePlaceholder: "Tell me what you are shaping...", sending: "Sending securely…", sent: "Message sent. I’ll get back to you soon.", successToastTitle: "Message received", successToastDescription: "Thanks — your note is safely on its way. I’ll reply soon.", emailOpened: "Your email client should open now.", error: "Something went wrong. Please email me directly.", active: "Secure Formspree delivery is active.", fallback: "Email fallback is active until a Formspree endpoint is added.", compose: "Compose email", defaultSubject: "Portfolio collaboration", nameError: "Please enter your name (at least 2 characters).", subjectError: "Please enter a subject (at least 3 characters).", messageError: "Please enter a message (at least 10 characters)." },
  },
  el: {
    nav: { home: "Αρχική", work: "Έργα", skills: "Ικανότητες", stack: "Stack", about: "Σχετικά", contact: "Επικοινωνία" },
    languageLabel: "Γλώσσα",
    primaryNavigation: "Κύρια πλοήγηση",
    brandHome: "Αρχική του Aggelos Frantzeskakis",
    themeLabel: "Θέμα",
    switchToDark: "Εναλλαγή σε σκοτεινό θέμα",
    switchToLight: "Εναλλαγή σε φωτεινό θέμα",

    github: "GitHub",
    linkedin: "LinkedIn",
    linkedinPending: "Αναμένεται το URL του LinkedIn",
    openNavigation: "Άνοιγμα πλοήγησης",
    closeNavigation: "Κλείσιμο πλοήγησης",
    navigation: "Πλοήγηση",
    closeMenu: "Κλείσιμο μενού",
    heroEyebrow: "Aggelos Frantzeskakis · Software Developer",
    heroTitle: "Κάνω το σύνθετο",
    heroAccent: "να μοιάζει ζωντανό.",
    heroDescription: "Δημιουργώ χρήσιμες ψηφιακές εμπειρίες γύρω από offline-first προϊόντα, local AI και interfaces που δίνουν στις φιλόδοξες ιδέες καθαρότερο τρόπο να κινηθούν.",
    exploreWork: "Δες τα έργα",
    seeSkills: "Δες τις ικανότητες",
    nowExploring: "Αυτή την περίοδο",
    heroSignature: "ανθεκτικά προϊόντα · τοπική νοημοσύνη",
    signatureStudy: "Ξεχωριστή μελέτη",
    flightPath: "01 / διαδρομή πτήσης",
    selectedWork: "Επιλεγμένα έργα",
    workTitle: "Έργα με",
    workAccent: "δική τους άποψη.",
    workAside: "Μια ζωντανή επιλογή από το τρέχον snapshot του GitHub. Άνοιξε μια κάρτα για focused study· τα ιδιωτικά έργα παραμένουν ξεκάθαρα σημειωμένα.",
    workHint: "Κάνε φυσικό scroll για να εξερευνήσεις κάθε κεφάλαιο.",
    skillsLabel: "Ικανότητες / τρέχουσα πρακτική",
    skillsTitle: "Χτίζω το σχήμα",
    skillsAccent: "γύρω από το σήμα.",
    skillsDescription: "Οι κατευθύνσεις που διατρέχουν τα τρέχοντα projects μου — πώς προσεγγίζω systems, ανθεκτικά προϊόντα και local intelligence.",
    skillTabsLabel: "Ομάδες ικανοτήτων",
    skillTabs: { systems: "Συστήματα", resilient: "Ανθεκτικότητα", intelligence: "Νοημοσύνη" },
    skillContent: {
      systems: { title: "Κάνω την πολυπλοκότητα προσβάσιμη.", text: "Σχεδιάζω product systems, ιεραρχίες πληροφορίας και responsive flows ώστε τα χρήσιμα εργαλεία να παραμένουν κατανοητά όσο μεγαλώνουν.", tags: ["Product thinking", "UX / UI", "Architecture", "Responsive web"] },
      resilient: { title: "Κρατώ την εργασία κοντά στον άνθρωπο.", text: "Με ενδιαφέρουν local-first συμπεριφορές, graceful states και εμπειρίες που διατηρούν την αξιοπρέπειά τους όταν χάνεται το δίκτυο.", tags: ["PWA", "Offline-first", "IndexedDB", "Local data"] },
      intelligence: { title: "Δίνω στο AI χρήσιμο ρόλο.", text: "Εξερευνώ local AI, RAG, provider routing και human-readable orchestration χωρίς να κρύβω το σύστημα πίσω από μαγεία.", tags: ["Local AI", "RAG", "Provider systems", "AI workflows"] },
    },
    stackLabel: "Tech stack",
    stackTitle: "Εργαλεία για ένα",
    stackAccent: "ζωντανό σύστημα.",
    stackAside: "Βασισμένο στις γλώσσες, τα patterns και τις AI κατευθύνσεις που αντιπροσωπεύονται στο τρέχον GitHub snapshot. Το stack είναι σκόπιμα επεκτάσιμο.",
    stackEvidence: "Σημερινά δεδομένα, αυριανός χώρος.",
    stackGroupLabels: ["Γλώσσες", "Product patterns", "AI κατεύθυνση"],
    stackNote: "Ό,τι βλέπεις εδώ προέρχεται από κώδικα που έχω πραγματικά υλοποιήσει.",
    skillsToolsTitle: "Τα εργαλεία πίσω από",
    skillsToolsAccent: "την πρακτική.",
    skillsToolsDescription: "Τα εργαλεία και οι τεχνολογίες που χρησιμοποιώ σε αυτά τα projects.",
    skillsToolsNote: "Εργαλεία & τεχνολογίες",
    skillsToolGroupLabels: ["Γλώσσα ανάπτυξης", "Resilient products", "Local intelligence", "Τρόπος παράδοσης"],

    aboutLabel: "Ο άνθρωπος πίσω από το έργο",
    aboutDescription: "Είμαι 19 ετών, αυτοδίδακτος developer από την Κρήτη. Χτίζω offline-first web apps και local-AI εργαλεία, κυρίως σε TypeScript και Python, και με νοιάζει το software να μένει γρήγορο, ιδιωτικό και κατανοητό. Τα περισσότερα repos μου είναι ιδιωτικά — τα δημόσια δείχνουν τον τρόπο που δουλεύω.",
    openGithub: "Άνοιγμα GitHub",
    copyHandle: "Αντιγραφή handle",
    copied: "Αντιγράφηκε",
    copySuccess: "Το GitHub handle αντιγράφηκε",
    copyError: "Δεν ήταν δυνατή η αντιγραφή του GitHub handle",
    cvReady: "Το CV είναι έτοιμο για λήψη",
    downloadStarted: "Η λήψη του CV ξεκίνησε",
    publicRepositories: "δημόσια repositories",
    preparingCv: "Προετοιμασία CV…",
    downloadCv: "Λήψη CV",
    contactLabel: "Ξεκίνα μια συζήτηση",
    contactPrompt: "Έχεις ένα καλό πρόβλημα;",
    contactTitle: "Ας δημιουργήσουμε",
    contactAccent: "κάτι αξιομνημόνευτο.",
    contactDescription: "Πες μου τι διαμορφώνεις. Το επόμενο βήμα μένει άμεσο, είτε μέσω Formspree είτε μέσω του email client σου.",
    backToTop: "Επιστροφή στην κορυφή",
    footerNote: "AF / κάθετο editorial portfolio",
    project: { private: "Ιδιωτικό", public: "Δημόσιο", privateKicker: "Ιδιωτικό build", publicKicker: "Δημόσιο project", openProjectPrefix: "Άνοιγμα λεπτομερειών για", studyLabel: "Μελέτη project", openDetails: "Άνοιγμα λεπτομερειών", fallback: "Ένα repository που διαμορφώθηκε μέσα από περιέργεια και επανάληψη.", detailFallback: "Αυτή η μελέτη δημιουργείται από το τρέχον snapshot του GitHub.", mixed: "Mixed", stars: "stars", forks: "forks", privateSource: "Όριο πηγής: ιδιωτικό", sourceGithub: "Η πηγή είναι διαθέσιμη στο GitHub", closeDetails: "Κλείσιμο λεπτομερειών", filterAll: "Όλα τα συστήματα", filterTypeScript: "TypeScript", filterPwa: "PWA / Web", filterAi: "AI / Local", filterPrivate: "Ιδιωτικά", emptyFilter: "Κανένα repository δεν ταιριάζει σε αυτό το φίλτρο. Δοκίμασε το 'Όλα τα συστήματα'." },
    cv: { previewCode: "Προεπισκόπηση εγγράφου / 01", close: "Κλείσιμο προεπισκόπησης CV", paperLabel: "Προεπισκόπηση CV", role: "Software & Product Developer", summary: "Δημιουργώ χρήσιμες ψηφιακές εμπειρίες γύρω από offline-first προϊόντα, local AI, resilient interfaces και thoughtful web experiences.", selectedWork: "Επιλεγμένα έργα", capabilities: "Ικανότητες", currentDraft: "Προεπισκόπηση CV", grounded: "Βασισμένο στο GitHub", confirmDetails: "Επικοινώνησε μέσω email", format: "PDF · A4", keepBrowsing: "Συνέχισε την περιήγηση", download: "Λήψη CV", openDirectly: "Άνοιγμα PDF απευθείας" },
    loader: { aria: "Φόρτωση portfolio του Aggelos", topLeft: "AF / digital craft", topRight: "Portfolio / 2026", calibrating: "Ρυθμίζω τη διαδρομή πτήσης", opening: "Ανοίγω το portfolio", signalCalibrating: "ΡΥΘΜΙΣΗ", signalOpening: "ΑΝΟΙΓΜΑ", bottomLeft: "Φορτώνω έναν χρήσιμο χώρο", bottomRight: "Κάνε scroll όταν είσαι έτοιμος ↓" },
    form: { name: "Το όνομά σου", namePlaceholder: "Όνομα", emailLabel: "Το email σου", emailPlaceholder: "you@example.com", emailError: "Δώσε ένα έγκυρο email για να μπορώ να απαντήσω.", subject: "Θέμα", subjectPlaceholder: "Ένα καλό πρόβλημα", message: "Μήνυμα", messagePlaceholder: "Πες μου τι διαμορφώνεις...", sending: "Ασφαλής αποστολή…", sent: "Το μήνυμα στάλθηκε. Θα σου απαντήσω σύντομα.", successToastTitle: "Το μήνυμα παραλήφθηκε", successToastDescription: "Ευχαριστώ — το μήνυμά σου στάλθηκε με ασφάλεια. Θα απαντήσω σύντομα.", emailOpened: "Το email client σου θα πρέπει να ανοίξει τώρα.", error: "Κάτι πήγε στραβά. Στείλε μου απευθείας email.", active: "Η ασφαλής παράδοση μέσω Formspree είναι ενεργή.", fallback: "Το email fallback είναι ενεργό μέχρι να προστεθεί Formspree endpoint.", compose: "Σύνταξη email", defaultSubject: "Συνεργασία μέσω portfolio", nameError: "Παρακαλώ εισάγετε όνομα (τουλάχιστον 2 χαρακτήρες).", subjectError: "Παρακαλώ εισάγετε θέμα (τουλάχιστον 3 χαρακτήρες).", messageError: "Παρακαλώ εισάγετε μήνυμα (τουλάχιστον 10 χαρακτήρες)." },
  },
} as const;
